### ISSUE TITLE
Using alpine image 

### ISSUE THREAD

**Issue by hdf1986** [automaticmode/active_workflow#4]
Hi! Just tried active_workflow on Heroku, and right now im starting to install it on my raspberry.

I was thinking of making a pull request for changing

```yaml
services:
  postgres:
    image: postgres:9.5
```

to

```yaml
services:
  postgres:
    image: postgres:9.5-alpine
```

Alpine is a small version of linux, it has some small differences with other distros, but at least for the database, the change should be transparent, and it consumes lot less space, ram, and cpu (You can read more about it on https://alpinelinux.org/about/)

What do you think about the change?
